## ****Air Quality Data Analysis****

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go


df = pd.read_csv("air_quality.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Dark mode for Matplotlib
plt.style.use("dark_background")

# Dark mode for Seaborn
sns.set_theme(style="darkgrid", context="notebook")

# Dark mode for Plotly
PLOTLY_TEMPLATE = "plotly_dark"

pollutants = ["pm25", "pm10", "no2", "o3", "co"]
numeric_cols = pollutants + ["synthetic_aqi"]
colors = None  # Let libraries choose their default colors

In [2]:
df

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...
527127,2023-01-16 09:00:00,D17,8.880395,17.091528,14.511241,27.730812,1.017884,27.0,Good,0,Normal
527128,2023-09-03 16:00:00,D18,14.708616,26.131330,21.595183,55.328278,0.718461,55.0,Moderate,0,Normal
527129,2023-01-31 12:00:00,D10,29.451436,52.058873,33.247696,39.081503,0.621691,73.0,Moderate,0,Normal
527130,2023-08-22 17:00:00,D12,53.340108,85.719320,54.080943,43.769245,0.860015,133.0,Unhealthy for Sensitive Groups,0,Normal
527131,2024-11-23 16:00:00,D09,11.978192,21.918493,15.918153,29.578698,0.640476,29.0,Good,0,Normal

#### ***PANDAS***

- **Display top 10 rows**

In [3]:
df.head(10)

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal
5,2025-05-28 00:00:00,D20,10.788017,22.500426,15.822771,22.926125,0.776106,26.0,Good,0,Normal
6,2023-09-01 20:00:00,D10,19.496830,37.542131,23.851285,40.002182,0.773935,48.0,Good,0,Normal
7,2024-03-23 23:00:00,D06,10.852200,22.266415,15.478677,8.552250,0.498035,27.0,Good,0,Normal
8,2024-02-20 04:00:00,D14,13.758044,18.978176,16.987760,9.429161,0.522662,34.0,Good,0,Normal
9,2024-03-04 06:00:00,D08,33.876804,59.456649,32.797248,29.351694,1.222775,84.0,Moderate,0,Normal

- **Display Bottom 10 rows**

In [4]:
df.tail(10)

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status
527122,2023-12-27 10:00:00,D04,12.858813,22.126397,26.124620,39.369817,0.815740,39.0,Good,0,Normal
527123,2023-11-22 14:00:00,D19,9.318693,20.714151,21.044877,38.418147,0.689358,38.0,Good,0,Normal
527124,2024-08-21 18:00:00,D16,13.045152,19.731938,20.571130,34.433981,0.821000,34.0,Good,0,Normal
527125,2024-02-13 16:00:00,D16,18.425170,31.278214,24.501329,39.699184,1.181168,46.0,Good,0,Normal
527126,2024-06-21 06:00:00,D05,15.725037,32.233944,21.658923,43.725179,0.930986,43.0,Good,0,Normal
527127,2023-01-16 09:00:00,D17,8.880395,17.091528,14.511241,27.730812,1.017884,27.0,Good,0,Normal
527128,2023-09-03 16:00:00,D18,14.708616,26.131330,21.595183,55.328278,0.718461,55.0,Moderate,0,Normal
527129,2023-01-31 12:00:00,D10,29.451436,52.058873,33.247696,39.081503,0.621691,73.0,Moderate,0,Normal
527130,2023-08-22 17:00:00,D12,53.340108,85.719320,54.080943,43.769245,0.860015,133.0,Unhealthy for Sensitive Groups,0,Normal
527131,2024-11-23 16:00:00,D09,11.978192,21.918493,15.918153,29.578698,0.640476,29.0,Good,0,Normal

**Shape of the dataset**

In [5]:
df.shape

(527132, 11)

**Column Names**

In [6]:
df.columns

Index(['timestamp', 'district_id', 'pm25', 'pm10', 'no2', 'o3', 'co',
       'synthetic_aqi', 'air_quality_category', 'pollution_alert_flag',
       'sensor_status'],
      dtype='object')

In [7]:
df.columns.tolist()

['timestamp',
 'district_id',
 'pm25',
 'pm10',
 'no2',
 'o3',
 'co',
 'synthetic_aqi',
 'air_quality_category',
 'pollution_alert_flag',
 'sensor_status']

**Data Types**

In [8]:
df.dtypes

timestamp               datetime64[ns]
district_id                     object
pm25                           float64
pm10                           float64
no2                            float64
o3                             float64
co                             float64
synthetic_aqi                  float64
air_quality_category            object
pollution_alert_flag             int64
sensor_status                   object
dtype: object

- **Missing values**

In [9]:
df.isnull().sum()

timestamp                  0
district_id                0
pm25                    5441
pm10                    5441
no2                     5441
o3                      5441
co                      5441
synthetic_aqi           5441
air_quality_category       0
pollution_alert_flag       0
sensor_status              0
dtype: int64

- **Missing-value percentage**

In [10]:
(df.isnull().mean() * 100).round(2)

timestamp               0.00
district_id             0.00
pm25                    1.03
pm10                    1.03
no2                     1.03
o3                      1.03
co                      1.03
synthetic_aqi           1.03
air_quality_category    0.00
pollution_alert_flag    0.00
sensor_status           0.00
dtype: float64

- **Duplicate rows**

In [11]:
df.duplicated().sum()

np.int64(1052)

- **Statistical Summary**

In [12]:
df.describe()

,timestamp,pm25,pm10,no2,o3,co,synthetic_aqi,pollution_alert_flag
count,527132,521691.000000,521691.000000,521691.000000,521691.000000,521691.000000,521691.000000,527132.000000
mean,2024-07-01 23:40:23.183566592,17.259193,30.886496,22.789367,33.768696,0.833976,49.923156,0.015649
min,2023-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.105382,2.000000,0.000000
25%,2023-10-02 00:00:00,9.320662,18.858760,14.708434,18.742482,0.593102,30.000000,0.000000
50%,2024-07-01 23:00:00,13.713142,25.803213,19.927996,32.207801,0.737591,43.000000,0.000000
75%,2025-04-01 23:00:00,20.823952,36.568153,27.842772,46.704131,0.973902,61.000000,0.000000
max,2025-12-31 23:00:00,119.192134,185.001350,169.678793,109.441409,6.984994,297.000000,1.000000
std,NaN,12.723393,19.318668,11.721318,19.540075,0.361331,30.220188,0.124113

- **Statistical summary including categorical columns**

In [14]:
df.describe(include="all")

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status
count,527132,527132,521691.000000,521691.000000,521691.000000,521691.000000,521691.000000,521691.000000,527132,527132.000000,527132
unique,NaN,20,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,3
top,NaN,D08,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,Normal
freq,NaN,26373,NaN,NaN,NaN,NaN,NaN,NaN,323467,NaN,521691
mean,2024-07-01 23:40:23.183566592,NaN,17.259193,30.886496,22.789367,33.768696,0.833976,49.923156,NaN,0.015649,NaN
min,2023-01-01 00:00:00,NaN,0.000000,0.000000,0.000000,0.000000,0.105382,2.000000,NaN,0.000000,NaN
25%,2023-10-02 00:00:00,NaN,9.320662,18.858760,14.708434,18.742482,0.593102,30.000000,NaN,0.000000,NaN
50%,2024-07-01 23:00:00,NaN,13.713142,25.803213,19.927996,32.207801,0.737591,43.000000,NaN,0.000000,NaN
75%,2025-04-01 23:00:00,NaN,20.823952,36.568153,27.842772,46.704131,0.973902,61.000000,NaN,0.000000,NaN
max,2025-12-31 23:00:00,NaN,119.192134,185.001350,169.678793,109.441409,6.984994,297.000000,NaN,1.000000,NaN
std,NaN,NaN,12.723393,19.318668,11.721318,19.540075,0.361331,30.220188,NaN,0.124113,NaN

- **Unique districts**

In [15]:
df["district_id"].unique()

array(['D11', 'D08', 'D02', 'D09', 'D14', 'D20', 'D10', 'D06', 'D04',
       'D17', 'D13', 'D03', 'D01', 'D16', 'D15', 'D19', 'D18', 'D07',
       'D12', 'D05'], dtype=object)

In [16]:
print(sorted(df["district_id"].unique()))

['D01', 'D02', 'D03', 'D04', 'D05', 'D06', 'D07', 'D08', 'D09', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20']

- **Air-quality category counts**

In [17]:
df["air_quality_category"].value_counts()

air_quality_category
Good                              323467
Moderate                          174369
Unhealthy for Sensitive Groups     21047
Unhealthy                           5877
Very Unhealthy                      2372
Name: count, dtype: int64

In [18]:
print(df["air_quality_category"].value_counts())

air_quality_category
Good                              323467
Moderate                          174369
Unhealthy for Sensitive Groups     21047
Unhealthy                           5877
Very Unhealthy                      2372
Name: count, dtype: int64

- **Sensor-status counts**

In [19]:
df["sensor_status"].value_counts()

sensor_status
Normal                521691
Communication-Loss      5339
Outage-Affected          102
Name: count, dtype: int64

In [20]:
print(df["sensor_status"].value_counts())

sensor_status
Normal                521691
Communication-Loss      5339
Outage-Affected          102
Name: count, dtype: int64

- **Pollution-alert counts**

In [21]:
print(df["pollution_alert_flag"].value_counts())

pollution_alert_flag
0    518883
1      8249
Name: count, dtype: int64

- **Date range**

In [22]:
print("Start:", df["timestamp"].min())
print("End:", df["timestamp"].max())

Start: 2023-01-01 00:00:00
End: 2025-12-31 23:00:00

- **Create year column**

In [23]:
df["year"] = df["timestamp"].dt.year
print(df[["timestamp", "year"]].head())

            timestamp  year
0 2024-05-01 22:00:00  2024
1 2023-11-21 06:00:00  2023
2 2024-09-02 10:00:00  2024
3 2025-03-14 23:00:00  2025
4 2024-09-10 07:00:00  2024

In [24]:
df.head()

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status,year
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal,2024
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal,2023
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal,2024
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal,2025
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal,2024

- **Create month column**

In [25]:
df["month"] = df["timestamp"].dt.month
print(df["month"].value_counts().sort_index())

month
1     44726
2     40892
3     44745
4     43275
5     44725
6     43284
7     44728
8     44726
9     43275
10    44727
11    43296
12    44733
Name: count, dtype: int64

In [26]:
df.head()

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status,year,month
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal,2024,5
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal,2023,11
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal,2024,9
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal,2025,3
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal,2024,9

- **Create month name column**

In [27]:
df["month_name"] = df["timestamp"].dt.month_name()
print(df["month_name"].value_counts())

month_name
March        44745
December     44733
July         44728
October      44727
August       44726
January      44726
May          44725
November     43296
June         43284
September    43275
April        43275
February     40892
Name: count, dtype: int64

In [28]:
df.head()

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status,year,month,month_name
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal,2024,5,May
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal,2023,11,November
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal,2024,9,September
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal,2025,3,March
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal,2024,9,September

- **Create hour column**

In [29]:
df["hour"] = df["timestamp"].dt.hour
print(df["hour"].value_counts().sort_index())

hour
0     21979
1     21970
2     21959
3     21960
4     21964
5     21964
6     21967
7     21963
8     21972
9     21962
10    21960
11    21971
12    21974
13    21958
14    21966
15    21956
16    21957
17    21964
18    21960
19    21959
20    21962
21    21961
22    21970
23    21954
Name: count, dtype: int64

In [30]:
df

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status,year,month,month_name,hour
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal,2024,5,May,22
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal,2023,11,November,6
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal,2024,9,September,10
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal,2025,3,March,23
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal,2024,9,September,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527127,2023-01-16 09:00:00,D17,8.880395,17.091528,14.511241,27.730812,1.017884,27.0,Good,0,Normal,2023,1,January,9
527128,2023-09-03 16:00:00,D18,14.708616,26.131330,21.595183,55.328278,0.718461,55.0,Moderate,0,Normal,2023,9,September,16
527129,2023-01-31 12:00:00,D10,29.451436,52.058873,33.247696,39.081503,0.621691,73.0,Moderate,0,Normal,2023,1,January,12
527130,2023-08-22 17:00:00,D12,53.340108,85.719320,54.080943,43.769245,0.860015,133.0,Unhealthy for Sensitive Groups,0,Normal,2023,8,August,17
527131,2024-11-23 16:00:00,D09,11.978192,21.918493,15.918153,29.578698,0.640476,29.0,Good,0,Normal,2024,11,November,16

- **Create day-of-week column**

In [31]:
df["day_name"] = df["timestamp"].dt.day_name()
print(df["day_name"].value_counts())

day_name
Sunday       75525
Monday       75514
Tuesday      75508
Wednesday    75501
Friday       75030
Thursday     75030
Saturday     75024
Name: count, dtype: int64

In [32]:
df

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status,year,month,month_name,hour,day_name
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal,2024,5,May,22,Wednesday
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal,2023,11,November,6,Tuesday
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal,2024,9,September,10,Monday
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal,2025,3,March,23,Friday
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal,2024,9,September,7,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527127,2023-01-16 09:00:00,D17,8.880395,17.091528,14.511241,27.730812,1.017884,27.0,Good,0,Normal,2023,1,January,9,Monday
527128,2023-09-03 16:00:00,D18,14.708616,26.131330,21.595183,55.328278,0.718461,55.0,Moderate,0,Normal,2023,9,September,16,Sunday
527129,2023-01-31 12:00:00,D10,29.451436,52.058873,33.247696,39.081503,0.621691,73.0,Moderate,0,Normal,2023,1,January,12,Tuesday
527130,2023-08-22 17:00:00,D12,53.340108,85.719320,54.080943,43.769245,0.860015,133.0,Unhealthy for Sensitive Groups,0,Normal,2023,8,August,17,Tuesday
527131,2024-11-23 16:00:00,D09,11.978192,21.918493,15.918153,29.578698,0.640476,29.0,Good,0,Normal,2024,11,November,16,Saturday

- **Average AQI by district**

In [34]:
df.groupby("district_id")["synthetic_aqi"].mean().sort_values(ascending=False)

district_id
D03    127.457177
D12     83.349933
D10     64.761717
D01     54.879580
D08     54.630811
D02     49.279420
D11     48.969920
D17     47.012876
D15     44.761230
D06     43.841841
D05     42.172460
D18     42.111746
D14     41.105859
D04     38.892694
D07     38.621073
D20     37.733374
D16     37.445058
D09     36.706780
D19     33.168424
D13     31.605007
Name: synthetic_aqi, dtype: float64

- **Average pollutants by district**

In [35]:
df.groupby("district_id")[pollutants].mean().round(2)

              pm25   pm10    no2     o3    co
district_id
D01          20.53  35.79  29.23  37.39  1.21
D02          17.41  31.13  26.33  37.22  1.15
D03          51.15  81.72  46.20  38.65  0.65
D04          12.23  23.34  19.46  31.97  0.88
D05          14.22  26.30  20.79  33.26  0.86
D06          15.29  27.91  20.92  33.52  0.80
D07          11.89  22.85  18.99  32.34  0.85
D08          20.77  36.15  26.36  35.68  0.92
D09           9.91  19.88  17.40  32.52  0.84
D10          25.59  43.39  27.56  33.18  0.69
D11          17.22  30.82  25.77  37.75  1.12
D12          33.43  55.15  32.85  31.39  0.64
D13           5.91  13.88  11.36  29.58  0.56
D14          13.22  24.84  19.03  34.15  0.76
D15          14.95  27.40  22.86  36.10  1.00
D16          10.63  20.93  16.94  33.02  0.75
D17          16.92  30.39  22.88  34.56  0.87
D18          14.88  27.32  20.08  30.80  0.75
D19           7.50  16.25  13.75  30.42  0.67
D20          11.53  22.31  17.04  31.86  0.70

- **Average AQI by air-quality category**

In [36]:
df.groupby("air_quality_category")["synthetic_aqi"].mean().sort_values()

air_quality_category
Good                               32.751185
Moderate                           66.710366
Unhealthy for Sensitive Groups    120.269802
Unhealthy                         170.295646
Very Unhealthy                    236.586706
Name: synthetic_aqi, dtype: float64

- **Monthly AQI summary**

In [37]:
monthly_aqi = df.set_index("timestamp")["synthetic_aqi"].resample("ME").mean()
monthly_aqi

timestamp
2023-01-31    45.259237
2023-02-28    45.170627
2023-03-31    46.835445
2023-04-30    48.348932
2023-05-31    52.311551
2023-06-30    55.910688
2023-07-31    56.934251
2023-08-31    56.600041
2023-09-30    50.928416
2023-10-31    48.837761
2023-11-30    46.472704
2023-12-31    45.800095
2024-01-31    44.918283
2024-02-29    46.182075
2024-03-31    46.864514
2024-04-30    48.554675
2024-05-31    50.849742
2024-06-30    56.865242
2024-07-31    56.756136
2024-08-31    55.265415
2024-09-30    51.790146
2024-10-31    48.000948
2024-11-30    46.194466
2024-12-31    45.289807
2025-01-31    45.544007
2025-02-28    44.781177
2025-03-31    46.710699
2025-04-30    48.919448
2025-05-31    51.932223
2025-06-30    57.294262
2025-07-31    56.612925
2025-08-31    54.666079
2025-09-30    52.201608
2025-10-31    48.916780
2025-11-30    45.860447
2025-12-31    45.988821
Freq: ME, Name: synthetic_aqi, dtype: float64