## ****Air Quality Data Analysis****

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go


df = pd.read_csv("air_quality.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Dark mode for Matplotlib
plt.style.use("dark_background")

# Dark mode for Seaborn
sns.set_theme(style="darkgrid", context="notebook")

# Dark mode for Plotly
PLOTLY_TEMPLATE = "plotly_dark"

pollutants = ["pm25", "pm10", "no2", "o3", "co"]
numeric_cols = pollutants + ["synthetic_aqi"]
colors = None  # Let libraries choose their default colors

In [2]:
df

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...
527127,2023-01-16 09:00:00,D17,8.880395,17.091528,14.511241,27.730812,1.017884,27.0,Good,0,Normal
527128,2023-09-03 16:00:00,D18,14.708616,26.131330,21.595183,55.328278,0.718461,55.0,Moderate,0,Normal
527129,2023-01-31 12:00:00,D10,29.451436,52.058873,33.247696,39.081503,0.621691,73.0,Moderate,0,Normal
527130,2023-08-22 17:00:00,D12,53.340108,85.719320,54.080943,43.769245,0.860015,133.0,Unhealthy for Sensitive Groups,0,Normal
527131,2024-11-23 16:00:00,D09,11.978192,21.918493,15.918153,29.578698,0.640476,29.0,Good,0,Normal

#### ***PANDAS***

- **Display top 10 rows**

In [3]:
df.head(10)

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status
0,2024-05-01 22:00:00,D11,13.845142,29.216811,22.758277,22.128768,1.341131,34.0,Good,0,Normal
1,2023-11-21 06:00:00,D08,23.617775,34.630069,31.060166,21.560664,1.066556,59.0,Moderate,0,Normal
2,2024-09-02 10:00:00,D02,15.465175,27.307933,28.727307,78.610070,1.123513,78.0,Moderate,0,Normal
3,2025-03-14 23:00:00,D09,4.054570,5.819488,9.511867,0.269460,0.569737,11.0,Good,0,Normal
4,2024-09-10 07:00:00,D14,29.953995,47.001299,44.735950,44.779858,1.587633,74.0,Moderate,0,Normal
5,2025-05-28 00:00:00,D20,10.788017,22.500426,15.822771,22.926125,0.776106,26.0,Good,0,Normal
6,2023-09-01 20:00:00,D10,19.496830,37.542131,23.851285,40.002182,0.773935,48.0,Good,0,Normal
7,2024-03-23 23:00:00,D06,10.852200,22.266415,15.478677,8.552250,0.498035,27.0,Good,0,Normal
8,2024-02-20 04:00:00,D14,13.758044,18.978176,16.987760,9.429161,0.522662,34.0,Good,0,Normal
9,2024-03-04 06:00:00,D08,33.876804,59.456649,32.797248,29.351694,1.222775,84.0,Moderate,0,Normal

- **Display Bottom 10 rows**

In [4]:
df.tail(10)

,timestamp,district_id,pm25,pm10,no2,o3,co,synthetic_aqi,air_quality_category,pollution_alert_flag,sensor_status
527122,2023-12-27 10:00:00,D04,12.858813,22.126397,26.124620,39.369817,0.815740,39.0,Good,0,Normal
527123,2023-11-22 14:00:00,D19,9.318693,20.714151,21.044877,38.418147,0.689358,38.0,Good,0,Normal
527124,2024-08-21 18:00:00,D16,13.045152,19.731938,20.571130,34.433981,0.821000,34.0,Good,0,Normal
527125,2024-02-13 16:00:00,D16,18.425170,31.278214,24.501329,39.699184,1.181168,46.0,Good,0,Normal
527126,2024-06-21 06:00:00,D05,15.725037,32.233944,21.658923,43.725179,0.930986,43.0,Good,0,Normal
527127,2023-01-16 09:00:00,D17,8.880395,17.091528,14.511241,27.730812,1.017884,27.0,Good,0,Normal
527128,2023-09-03 16:00:00,D18,14.708616,26.131330,21.595183,55.328278,0.718461,55.0,Moderate,0,Normal
527129,2023-01-31 12:00:00,D10,29.451436,52.058873,33.247696,39.081503,0.621691,73.0,Moderate,0,Normal
527130,2023-08-22 17:00:00,D12,53.340108,85.719320,54.080943,43.769245,0.860015,133.0,Unhealthy for Sensitive Groups,0,Normal
527131,2024-11-23 16:00:00,D09,11.978192,21.918493,15.918153,29.578698,0.640476,29.0,Good,0,Normal

**Shape of the dataset**

In [5]:
df.shape

(527132, 11)

**Column Names**

In [6]:
df.columns

Index(['timestamp', 'district_id', 'pm25', 'pm10', 'no2', 'o3', 'co',
       'synthetic_aqi', 'air_quality_category', 'pollution_alert_flag',
       'sensor_status'],
      dtype='object')

In [7]:
df.columns.tolist()

['timestamp',
 'district_id',
 'pm25',
 'pm10',
 'no2',
 'o3',
 'co',
 'synthetic_aqi',
 'air_quality_category',
 'pollution_alert_flag',
 'sensor_status']

**Data Types**

In [8]:
df.dtypes

timestamp               datetime64[ns]
district_id                     object
pm25                           float64
pm10                           float64
no2                            float64
o3                             float64
co                             float64
synthetic_aqi                  float64
air_quality_category            object
pollution_alert_flag             int64
sensor_status                   object
dtype: object

- **Missing values**

In [9]:
df.isnull().sum()

timestamp                  0
district_id                0
pm25                    5441
pm10                    5441
no2                     5441
o3                      5441
co                      5441
synthetic_aqi           5441
air_quality_category       0
pollution_alert_flag       0
sensor_status              0
dtype: int64

- **Missing-value percentage**

In [10]:
(df.isnull().mean() * 100).round(2)

timestamp               0.00
district_id             0.00
pm25                    1.03
pm10                    1.03
no2                     1.03
o3                      1.03
co                      1.03
synthetic_aqi           1.03
air_quality_category    0.00
pollution_alert_flag    0.00
sensor_status           0.00
dtype: float64